# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ttsx_cart',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='名字')),
                ('gpic', models.ImageField(upload_to='df_goods', verbose_name='图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='价钱')),
                ('is_delete', models.BooleanField(default=False)),
                ('gunit', models.CharField(default='千克', max_length=20, verbose_name='单位')),
                ('gclick', models.IntegerField(default=0, verbose_name='点击')),
                ('gjianjie', models.CharField(max_length=200)),
                ('gstock', models.IntegerField(verbose_name='库存')),
                ('gcontent', tinymce.models.HTMLField(verbose_name='描述')),
            ],
            options={
                'db_table': 'ttsx_goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20, verbose_name='种类')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ttsx_typeinfo',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeInfo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel'),
        ),
    ]
