# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.CharField(max_length=30, verbose_name='电子邮箱')),
                ('showname', models.CharField(default='', max_length=20, verbose_name='收件人名字')),
                ('showaddress', models.CharField(default='', max_length=100, verbose_name='收件地址')),
                ('showpostcode', models.CharField(default='', max_length=6, verbose_name='收件邮编')),
                ('showtel', models.CharField(default='', max_length=11, verbose_name='收件人电话')),
            ],
            options={
                'db_table': 'ttsx_user',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=256)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
            options={
                'db_table': 'ttsx_user_ticket',
            },
        ),
    ]
